### ISSUE TITLE
Allow ConvertToString Function not throw exception on null input

### ISSUE THREAD

**Issue by weyto** [Microsoft/MIMWAL#47]
Dear nilesh
We use the ConvertToString Function really often. In most cases to save ObjectID's in a string attribut.
On a direct mapping (of a reference attribut as Source to an string attribut as Target) MIMWAL doesn't recognize that the both field's are exactly the same. This ends up that everytime the workflow is triggered the values are generating a new request to update the string Attribut. But there is no update, because the values are the same.
This szenario can be fixed with the function ConvertToString. In this case MIMWAL recognize that both values are equal and no futher request will be committed.
The problem is, if the value are null() (because the reference attribut is not set) an exception will be throw. The same is when we set up an IIF(IsPresent()) before. MIMWAL want to try to resolve the complete statement and of course then an exception will be throw.
Does something speak against that the function ConvertToString() will not throw an exception on null valued parameter? In this case it should return null.

Best regards,
Thomas

**Comment by NileshGhodekar** [comment]
Probably a good suggestion, but will need to confirm if there is any backward compatibility issues, but you can always do an IIF IsPresent() check that returns an empty string instead of Null() and feed that to ConvertToString, no? something like ConvertToString(IIF(IsPresent(ObjectID), ObjectID, "")). Does this not work?

**Comment by weyto** [comment]
Interesting idea to set the IIF Function as the parameter of the ConvertToString function.
I have tested this and have no futher exceptions.
But now i have everytime when the workflow triggers a futher request which updates the String Value Attribute to String.Empty. So MIMWAL does not recognize that the Target Value are the same (in case of String.Empty).

**Comment by NileshGhodekar** [comment]
I've updated the behaviour of ConvertToString to return null if the input parameter is null. You'll need to get the source code directly from https://github.com/Microsoft/MIMWAL/archive/master.zip as not planning on making a new separate release for this.

PS: Ideally you want to prevent the unnecessary workflow from firing as running WF is much more processing. Just curious, do you see FIM running any workflow if there is no change to the data due to the request or does it just silently skips the request?

**Comment by weyto** [comment]
Hi Nilesh
Thanks a lot for the pull request and the modifications.
One thing about your comment:
We discuss this topic a lot time by our team. What's the best way to structure the workflows and mpr's. In my opinion there are two possible ways to structure in case of calculating multiple attributes on a object.
1. For every Attribut a single workflow and mpr.
2. Combine multiple Attributes to a single worklflow and mpr.

Let me attach a little (really basic Szenario):
1. Calculating of a DisplayName based on Firstname, LastName and perhabs an other object like OrganizationalUnit.
2. Calculating the manager and Department Attribut based on the OrganizationalUnit object.

So these Szenario can implemented with option 1 and option 2.
Option 1 has the benefit that in case of changing the OrganizationalUnit all Attribute (DisplayName, OrganizationalUnit and Manager) will be processed in one PostRequest (after modified the OrganizationalUnit Attribut (which is an reference). But i agree with you there can be some overhead in case of only modify the FirstName, because in this case only the DisplayName must be reevaluate.

Option 2 in contrast to Option 1 hasn't this overhead. In this implementation every calculated Attribut will be reevaluate based on changes which result in a change of the calculated Attribut. Like FirstName, LastName or OrganizationalUnit results in a change of the DisplayName. But this will result in many PostRequest (on creation or modify multiple Attributes), because every PostRequest only change one Attribut.

Now: What's the best way?
Actual we haven't some large Performance comparsion of this two options. We implement in most case with option 1. This prevents the generation of many PostRequest. It will be very interesting how you and other community members thinking about that.

**Comment by NileshGhodekar** [comment]
Well, the thumb of rule answer is whatever will result in minimum number of workflows to complete the request. Generally, you'd think that is Number 2 - combining will result in minimum number of workflows than Number 1.

**Comment by bpalfaro** [comment]
@weyto - Overall, my vote would be to minimize the MPRs and Workflows as much as possible and break apart as needed.

@weyto - In your scenario, if your OU changes then you must evaluate the Manager and Department.  To me, this sounds like you need to isolate this functionality to its own MPR.  So, I would keep both in your basic scenario.  Remember, if a user changes a first name and the calculated OU doesn't change, MIM optimizes this update and does not fire the second MPR.  As for your second MPR, not sure how you are performing the update, but if you build two MIMWAL update activities one for Manager lookup and one for Department lookup and store into WorkflowData, then a final update activity to set Target Manager and Department, you would optimize your update to one post request..  This may not be obvious initially but if that's your concern it's solvable.

Some other best practices I have seen on MPRs is that separating out grant permissions and email notification MPRs can be helpful.  Especially, the email notification MPRs because you can turn off all email notifications easily for a deployment to production and then turn them back on.
