### ISSUE TITLE
.NET Framework 3.5 SDK Availability

### ISSUE THREAD

**Issue by pittochs** [Microsoft/MIMWAL#56]
The link the the .NET Framework 3.5 SDK takes you to a Microsoft page that says the download is no longer available.

**Comment by NileshGhodekar** [comment]
Thanks for reporting this. I guess I'm just going to remove the hotlink to the SDK. People then can get those utilities from the GitHub initial check-in itself (already hotlinked).

**Comment by lehtoj** [comment]
I've downloaded the files mentioned in the wiki separately to the specified locations. However, the build still fails.

Even though the projects target .NET Framework 3.5, Visual Studio 2015 attempts to build the solution using .Net 4.

```
1>------ Rebuild All started: Project: WorkflowActivityLibrary, Configuration: Release Any CPU ------
1>C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Workflow.targets(121,5): error : Compilation failed. Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
2>------ Rebuild All started: Project: WorkflowActivityLibrary.UI, Configuration: Release Any CPU ------
2>CSC : error CS0006: Metadata file 'C:\MIMWAL-2.18.0318.0\src\WorkflowActivityLibrary\bin\Release\MicrosoftServices.IdentityManagement.WorkflowActivityLibrary.dll' could not be found
========== Rebuild All: 0 succeeded, 2 failed, 0 skipped ==========
```

**Comment by NileshGhodekar** [comment]
This is a different issue than the issue for which this thread was opened. Here it seems like when you installed VS 2015, it did not install the .NET 3.5 workflow components?

**Comment by lehtoj** [comment]
All I can say for certain that I've installed VS 2015, put the files in the MIMWAL wiki in their place, ran rebuild. Which then fails to the error described above. In the individual projects in the MIMWAL solution, the target is 3.5. I cannot tell if I actually have the 3.5 SDK installed, because I cannot find it anywhere so I could install it to make sure.

**Comment by NileshGhodekar** [comment]
You don't need SDK installed, you only need those two specific utilities from the SDK. These two utilities does not play any part in the build/compilation step that is reporting error.  If you try to create a brand new Workflow project, does VS allows you to a new .NET 3.5 Workflow Activity Library? If not, try rerunning the VS installer with "Custom" setup and see what .NET 3.5 WF optional component you need to install.

**Comment by NileshGhodekar** [comment]
Ok, so I did a VS 2015 fresh install on a WS2012 R2 server. All I needed was to turn on the .NET 3.5 feature on the server and default install of VS 2015.

**Comment by NileshGhodekar** [comment]
I'm closing this Issue now as the I've updated the Build wiki for the original issue reported (.NET 3.5. SDK not available for download any more and have provided instructions on workaround). @lehtoj, if you still have issue with VS 2015 and .NET 3.5 WF projects, probably do a reinstall or post this on a Visual Studio forum. Thanks!

**Comment by LaLaLeen** [comment]
I had the same error; within the "errorlog" we had :\Windows\Microsoft.NET\Framework\v4.0.30319\Workflow.targets(121,5): error : Compilation failed. Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
and
MicrosoftServices.IdentityManagement.WorkflowActivityLibrary.dll' could not be found

.NET 3.5 was installed.
We installed the tool on a windows 2016 server. 
Seems if you download the files, they files get a property enabled "Security: This file came from another computer and might be blocked to help protect this server". When unblocking the all files, this issue was solved. The URL below triggered me.
https://projectkbblog.wordpress.com/2017/07/12/re-building-workflows-for-mim-2016-compilation-failed-unable-to-load-one-or-more-of-the-requested-types/

**Comment by RobinBeismann** [comment]
> I had the same error; within the "errorlog" we had :\Windows\Microsoft.NET\Framework\v4.0.30319\Workflow.targets(121,5): error : Compilation failed. Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
> and
> MicrosoftServices.IdentityManagement.WorkflowActivityLibrary.dll' could not be found
> 
> .NET 3.5 was installed.
> We installed the tool on a windows 2016 server.
> Seems if you download the files, they files get a property enabled "Security: This file came from another computer and might be blocked to help protect this server". When unblocking the all files, this issue was solved. The URL below triggered me.
> https://projectkbblog.wordpress.com/2017/07/12/re-building-workflows-for-mim-2016-compilation-failed-unable-to-load-one-or-more-of-the-requested-types/

Thanks, unblocking the files solved it for me aswell.
Heres a quick PowerShell Cmdlet for it: `Get-ChildItem -Recurse -Path "C:\src" | Unblock-File`
