### ISSUE TITLE
Wiki update Build and Deployment

### ISSUE THREAD

**Issue by gibazza** [microsoft/MIMWAL#77]
VS2017 and 2019 and can be used to build the MIMWal solution. Need to ensure that the Office/SharePoint Development workload is installed and the optional Windows Identity Foundation 3.5 component.
![Annotation 2019-07-16 171205](https://user-images.githubusercontent.com/15247540/61310792-e786c380-a7ec-11e9-900c-08dbb6a0437e.png)

**Comment by NileshGhodekar** [comment]
Thanks @gibazza! I've updated the B&D wiki with a link to this thread since you have a screenshot. Please see the previous Issue #71 on the subject for a fully qualified disclaimer.

**Comment by KentNordstrom** [comment]
Looks like the WIF 3.5 is not available in VS2017... at least not in my setup... but could be because my dev machine is lacking te older .NET versions installed (running new install of Windows 10)
![image](https://user-images.githubusercontent.com/12670764/87765848-9c94f700-c818-11ea-8f46-4c8e7069afb0.png)

**Comment by NileshGhodekar** [comment]
@KentNordstrom, there is no dependency on WIF 3.5, but only on .NET 3.5.
