### ISSUE TITLE
MIM Portal ignoring extra lines in xoml

### ISSUE THREAD

**Issue by woolfep** [microsoft/MIMWAL#93]
I'm reading the xoml from the workflow definition via powershell and trying to add an extra row for update resources.  then reimporting the xoml back to the workflow.

The extra lines are added into the xml but MIM is ignoring these lines  and not creating the extra rows. What am i doing wrong?
Powershell:
[mimxoml.ps1.txt](https://github.com/microsoft/MIMWAL/files/5354201/mimxoml.ps1.txt)
ResultingXOML - I have reduced the xml to just the activity its regarding If you need the full  xoml I can provide it also
[xomldata.txt](https://github.com/microsoft/MIMWAL/files/5354218/xomldata.txt)

**Comment by woolfep** [comment]
Update the issue is with the node containing count. If i manually up it -  the extra lines appear but if, in powershell, i try to replace the node with a clone where i alter the childnodes value or innertext properties I causes an error

**Comment by NileshGhodekar** [comment]
Hi @woolfep, I'm closing this issue for two reason: 1. What you are going is not really supported because XOML for any .NET workflow should be produced by a serialisation process and  2. This is not related to MIMWAL. Having said that the method is not really supported, if you still want to do this (because at the end of the day it's an XML text), you simply need to do your workflow manually using the UI first and compare it what your script is producing to see what is different and and go from there.
